# Generated by Django 5.2.17 on 2026-09-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeDolbeau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='courriel',
            field=models.EmailField(blank=True, max_length=254, verbose_name='courriel'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='numéro de téléphone'),
        ),
    ]
