# Generated by Django 5.2.17 on 2026-09-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeDolbeau', '0006_alter_transactioncafe_type_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nombre_cafes_gratuits',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de cafés gratuits'),
        ),
    ]
