# Generated by Django 5.2.17 on 2026-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeDolbeau', '0007_client_nombre_cafes_gratuits'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('telephone', ''), _negated=True), fields=('telephone',), name='client_telephone_unique_non_vide', violation_error_message='Ce numéro de téléphone est déjà associé à un client.'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('courriel', ''), _negated=True), fields=('courriel',), name='client_courriel_unique_non_vide', violation_error_message='Ce courriel est déjà associé à un client.'),
        ),
    ]
