# Generated by Django 5.2.17 on 2026-09-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='nom complet')),
                ('telephone', models.CharField(max_length=30, verbose_name='numéro de téléphone')),
                ('courriel', models.EmailField(max_length=254, verbose_name='courriel')),
                ('nombre_cafes_achetes', models.PositiveIntegerField(default=0, verbose_name='nombre de cafés achetés')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['nom_complet'],
            },
        ),
    ]
