# Generated by Django 5.2.17 on 2026-09-23 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeDolbeau', '0002_alter_client_courriel_alter_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_cafe', to='CafeDolbeau.client')),
            ],
            options={
                'verbose_name': 'transaction de cafés',
                'verbose_name_plural': 'transactions de cafés',
                'ordering': ['-date_creation', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite__gte', 1)), name='transaction_cafe_quantite_positive')],
            },
        ),
    ]
