# Generated by Django 5.2.17 on 2026-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeDolbeau', '0003_transactioncafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nombre_cafes_prepayes',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de cafés prépayés'),
        ),
        migrations.AddField(
            model_name='transactioncafe',
            name='type_transaction',
            field=models.CharField(choices=[('achat', 'Cafés achetés'), ('prepaye', 'Cafés prépayés')], default='achat', max_length=10, verbose_name='type de transaction'),
        ),
    ]
