# Generated by Django 5.2.17 on 2026-09-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeDolbeau', '0004_client_nombre_cafes_prepayes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncafe',
            name='type_transaction',
            field=models.CharField(choices=[('achat', 'Cafés achetés'), ('prepaye', 'Cafés prépayés'), ('gratuit', 'Cafés gratuits')], default='achat', max_length=10, verbose_name='type de transaction'),
        ),
    ]
