# Generated by Django 5.2.17 on 2026-09-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeDolbeau', '0005_alter_transactioncafe_type_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncafe',
            name='type_transaction',
            field=models.CharField(choices=[('achat', 'Cafés achetés'), ('prepaye', 'Cafés prépayés'), ('gratuit', 'Cafés gratuits'), ('utilise', 'Cafés prépayés consommés')], default='achat', max_length=10, verbose_name='type de transaction'),
        ),
    ]
